---
title: "倒计时为负的三百六十五个日月"
author: "D"
editor: visual
---

（四）

金昇玟从来不是那种会把誓言抛向风口、让诺言挂在云端的人。他总觉得那太轻太虚，不如实实在在，将心意藏在日常里。这既是对现实的妥协，也是某种清醒的自律。他相信人可以浪漫，但若能始终保持一丝冷静，就不会被骤然而起的热情冲昏头脑。

他最烦李龙馥的莽劲儿。那种莽撞不是盲目，而是对结果的漠然，好像他一旦下了决心，无论结局如何，都能独自消化，也能坦然接受。昇玟不明白，这是一种怎样的心态？龙馥就像被困在自己亲手设下的牢笼里，却又在其中自由自在。他对自己有一种近乎本能的信任，好似永远不会背弃内心的某种教条。固执得像一根不断被拉伸、却绝不折断的拉力带，弹性中带着危险，却又让人无法移开目光。

李龙馥身上总有割裂：自信与不安并生，清醒与莽撞共存。他对自己的认知极其清楚，却对昇玟眼中那个“李龙馥”毫不在意。甚至，他觉得打破昇玟的目光、推翻昇玟的定义，比被理解更有意义。仿佛在那一次次自我拆解中，他才能证明自己的存在。

这是为什么呢？金昇玟有在好好反省这个问题，他觉得李龙馥这个人，其实是有点小心眼的。他不是一个喜欢被人看透的家伙，但是金昇玟却觉得，他是这个世界上最理解李龙馥的人。龙馥时常因为他的妄自菲薄而感到懊恼。他不会否认金昇玟说，呀我不是这样想的，而是平静地看他一眼，瞥过头，选择性地翻过这一篇章。

金昇玟每逢这种时候，就格外心虚。他这才真切体会到“年下”的自知之明——明明只是比哥哥小了一个礼拜，却总觉得自己像个被惯坏的小孩，反倒老是想去顺着哥哥的脾气。他心里暗暗发誓，要同仇敌忾地帮哥哥把怒火撒回去，好像这样才算尽到了弟弟的本分。

可不知怎么的，他总是有些拿不准的小心思。真要火上浇油时，他又舍不得。于是便想出些拐弯抹角的法子：假借队友之口，暗搓搓地使点叛逆的小坏心思。别人说哥哥爱撒娇，他就别扭地抱怨一句哥哥脾气坏；别人笑哥哥笨手笨脚，他偏要反驳，说他其实有过超乎寻常的发挥。看似拗口，实则偏袒。昇玟自己也清楚，这点小心眼，就像藏不住的光，总归会被哥哥看穿。

偏偏李龙馥就爱听这些，他就是喜欢看着昇玟躲开他目光时的狼狈，喜欢在听到时眼睛眯成了弯月，勾着唇笑得无声，有时手脚还能跟着并用，像极了小时候被家里人夸奖得到了小红花的孩子。昇玟心里一紧，面上却还是要装作不耐烦，那是他俩一种无声的秘密。

就像谈论所爱之物的最佳方式是轻描淡笑，因为心灵相通，所以害怕过重地撩拨这根心弦(1)。他不愿意承认这点，两人就像在同一块帷幕后行走，影子时而重叠，时而分离，却谁都没有去揭开那层布。那无声的力场便在暗处延展，没有形状，也没有声音，却悄然改变了他们的轨迹。

因此，有时影子相叠时，无声也成了一种慰藉。

而龙馥似乎正喜欢这样，他喜欢看着昇玟被爱着，被许多人爱着，甚至忍不住一次次去强调这一点。他像个置身事外的围观者，乐于看昇玟对着其他队友撒娇胡闹，乐于在喧闹里旁观那份热烈。龙馥的爱包罗万象，昇玟想，或许这就是一种博爱吧。

龙馥会笑昇玟因为大哥的关心而感动到落泪，会跟着起哄他和二哥最火热的 CP，会在争三哥宠时和他胡闹打趣；会津津乐道地加入哥哥们关于昇玟撒娇的讨论，也会在忙内组里对着两个弟弟夸张地感叹他们的互动。但奇怪的是，他却很少主动与其他人分享关于昇玟的片段。
没人觉得这有什么异常。龙馥自己也从不提起，仿佛一切都理所当然。他若真要说起，也只会去用毫不掩饰的热情，提一些盛满真诚的喜欢与夸奖。不知怎的，偏偏在夸奖昇玟时，他的耳根会发红，脖颈微缩，眼神闪烁，动作零碎，像是在用一场自说自话的独角戏，说服自己去平复那份突如其来的慌乱。

昇玟有时会半开玩笑似说，咏卟噶，你到底喜不喜欢我啊！

问题听上去莫名其妙，答案却从来不用怀疑。若是玩笑语气，龙馥会回一句“不，我最不喜欢你了”；若是认真的口吻，他又会理所当然地说：“当然了，谁不会喜欢我们可爱的昇mo呢？” 他们都心知肚明，就像一年四季周而复始，日升月落，龙馥的爱是慷慨的，是盛夏，是一片金色的向日葵田，追随着太阳，赠送着热与光亮。

昇玟很想告诉他，他偶尔也是会贪心的，他宁愿有时希望龙馥的炽烈，不是那田野般铺展的花海，而是一株盛放到极致的曼陀罗花，拥抱能濡旗帜般燃烧。

可他能凭什么说出口呢？

他不会像龙馥，指着大海说昇玟呀，你看那很像你。

昇玟会问他说，是海鸥还是大海？

龙馥告诉他，是海鸥也是大海。

他说大家的昇玟是海鸥，龙馥的昇玟像深海。

潮汐起落，月光摇曳，宁静，却波澜壮阔，是静默的温度。它的仅有，也是它的温柔。

昇玟很苦恼，说我不觉得自己像深海哎。

龙馥只能说出昇玟像大海这种不着调的比喻，他绞尽脑汁也憋不出什么生动的描述，于是他转移了话题，问那你觉得自己像什么？

金昇玟思忖了会儿，没开口。他是个文科生，但形容起自己来倒像极了个笨拙的理科男。觉得用什么话来形容都很是拗口。

李龙馥这会儿突然一把捧起他的脸，嘟囔起来说啊，昇玟这人怎么这么可爱。今天头发长长得，染了色像金毛了，虽然康哈吉更合适啦，但这几天先做个小金毛吧。

金昇玟想拍开他的手，还没来得及，李龙馥又伸过来，边揉边笑，哎一古，怎么懵懵得，可爱可爱。

这又是个文字游戏，金昇玟想，李龙馥想知道的是哪个答案？金昇玟猜测的龙馥眼里的金昇玟，还是金昇玟眼里的自己？

他没有回答龙馥的问题。出道很久后，龙馥就没再直率地夸他可爱了。让龙馥说出可爱这个夸奖词是件很难的事，就像让他主动地和队友说今天昇玟又和我说了什么，做了什么。昇玟想多听他说上几句，所以他不动了。

可这会儿李龙馥又不说了。他替他捋了捋头发，端详了会儿，又故意把那一头好不容易抚平的杂毛弄乱，欠抽似的，逼他说话。

金昇玟只好低声质问他到底要干嘛。

他说话的时候很少会把嘴张得很大，心情不佳时更是如此，字眼含糊，像在赌气。

龙馥道我前几天上网的时候看到一个说法，说上唇薄的人，都比较寡情哎。

昇玟问你是在说我吗？

不是的，李龙馥摇摇头，我就是觉得这说法不太可靠。

他过了会儿又说，前几天哥说声音低的人都是花蝴蝶，我知道这个梗，说是容易出轨...花蝴蝶是会出轨的意思吗？

金昇玟瞥了他一眼，说你不是都知道了吗？

李龙馥不甘示弱地追问，那昇玟觉得我是会出轨的人嘛？

昇玟看着他，没马上开口，他想说你不会，你看着像是会平等地去爱所有人的人，但是你的爱是生命力，是火苗，是焚烧，不是爱情，也不会是爱情。

那是什么样的一种爱？是没有目的性的爱，是一种动力。就像龙馥本身，对昇玟而言，像是被阳光与颜色调制出来的孩子，有草地的绿色，天空的湛蓝，偶尔像是一副被烈日点燃的画布，迸溅的颜色，挥洒着颜料，像被染料泼洒过的山谷，浓烈、跳脱。

龙馥突然扑上来，伸手去抓他。不满来得毫无预兆，好像只是因为对方没有给出答案。他的动作是暴烈的，想法是冲动的。可昇玟的沉默却像炸响的惊雷，他只能死死攥住昇玟的袖子，一双眼睛固执地和他对视，在没有得到任何退让后，几乎带着恫吓般低声说，

他说我要哭了，昇玟。

他当然没有。只是低头吻住了他，叼住他的上唇，用牙尖一点点磨蹭。那力道锐利而不至于咬破，痒与痛交织。昇玟早有防备，却仍旧被他扑来的香水味浇灌得措手不及——木质的底调里淋上斑斑果香，像淬了迷魂药的熏烟，搅得他头昏目眩。

直到血腥味弥漫开来，龙馥才停下，急促地喊说昇玟你怎么可以把我当人渣了！你太过分了。

金昇玟下头，许久才抬起，轻轻蹭了蹭他的手背。这是他一贯不好意思道歉时的方式。

他们的关系总是微妙得近乎失衡。和别人一起时理所当然的举动，落在他们身上却像尴尬的参照，不如彻底不营业来得痛快。昇玟偶尔会心生不甘，可龙馥似乎总是无所谓——无所谓到，仿佛在别人眼里，他和昇玟的亲疏都无足轻重。

只是没想到，私下里却会换来这样固执而激烈的反抗。固执的李龙馥，像一树猩红的石榴花，在傍晚的天空下燃烧；也像夏季骤然暴起的雷雨，猛烈、肆意，草木被打湿，天空被击穿，而空气因此透亮。

金昇玟从未对旁人说起过，他总觉得那一刻的自己，就像雨后初晴跑出来的孩子，仍在学会如何在水坑中找到乐趣，仍在大口呼吸雨洗过的空气。就在那时，他恍若也得到了一份救赎。他想，与其说是对龙馥的默许，不若说是对自己的放纵，好像这一刻，得到解放的是自己，而非对方。他俩何谈相互救赎和解放，不过是两个孩子，在雨后的花园里瑟缩着靠在一起。草叶上挂着斑斓的水珠，天空被撕开一条彩虹，湿漉漉的空气里浮动着泥土与花香四周空旷，只有他们安静的呼吸，像是在一块画布上抹上了两道亮光。

（1)加缪
---
