---
title: "倒计时为负的三百六十五个日月"
author: "D"
editor: visual
---
(五）

其实不光是队友，就连金昇玟自己，都很少能从李龙馥的口中真正听见关于“金昇玟”这个人的模样。在他嘴里，昇玟总像个百变小樱。今天因为认真劳作而显得很男人，明天却又在宜家仗着他不好发作买了一堆他嫌弃的玩意儿，转眼就痛失“优秀室友”的名号。

龙馥说我喜欢百变小樱这个说法，百变小樱金昇玟，下次安可你不穿你跟我姓。

金昇玟愤怒地说你怎么又给我扯那么远，我真是，正经说话的时候和你就是没法说到一块去！

李龙馥学着他说话的调调，那我为什么非要和你说到一块去！我什么时候说你是百变小樱了！你自己非要当，我有什么办法。

这话他说得言之凿凿，有理有据，于是，金昇玟又成了哑巴，李龙馥对着他的挑衅无动于衷，耸耸肩说我打游戏去了。金昇玟不喜欢这样的李龙馥，他闷闷地坐在那儿，觉得那些话明明像是邀请，落在他身上却又冷淡得不动声色。

他说龙馥啊，我实在有一天会忍不住问你这个问题的。

李龙馥看也没看他，就直接说，我以前就说过啊，昇玟尼是最重要的，从来都不会变。

金昇玟站起来，低着头跟在他身后，一步一步，不超也不并行，只在他身侧晃悠。他小声道你也知道我想说什么啊，龙馥哎，你要我怎么才能忍住不和你确认。

李龙馥突然刹住了脚，说这需要证明吗？我还觉得有时候自己炫耀过头了哎，哥都有时候说要让我收敛些。

金昇玟一双狗耳朵像是立刻竖了起来，问哪个哥哪个哥！彬哥还是灿哥，你说啊你说啊你说啊！

李龙馥又不想和他说了，不耐烦地甩开他攀上来手问他你玩不玩游戏？

金昇玟笑嘻嘻地去勾他的肩膀说玩嘛玩嘛，哪个哥那么关注我呀？

到底是个兄控，李龙馥翻了个白眼，他想，反正我也是兄长，大了七天也是哥哥，也能沾点边儿，我管你最喜欢哪个哥哥，最想要哪个哥哥关注，我偏偏就不随你的意，让你瞎猜，让你胡蒙。

他搪塞了个说法，说我不记得了，说你再这样我就要开始不喜欢你了。他的韩语还没有学出母语者的精髓，也不知道自己是不是词不达意。在李龙馥看来，金昇玟在公共场合对他的那些举动，总有一种别人无法替代的意味。旁人眼里或许只是寻常的玩笑、轻快的互动，可在他心里，却像被悄悄留下了标记，带着只属于自己的分量。他喜欢金昇玟把这种喜欢展露出来，仿佛把他也包裹进了那个小小的世界里。只是这份融合最好不要像易碎的泡泡，相撞时太过脆弱。因为那种心底涌起的不加掩饰的得意，一旦赤裸裸地摊开在对方面前，便会添上一丝卑怯。

金昇玟被他这么一甩手，反而心情好了起来，说今天我带你飞，你想输几把都可以。

他心情好起来不加掩饰，整个人都跟着更加得神气活现，尾音都带着股上扬的调调，有一种大梦初醒后终于恢复了精神。

李龙馥向来是对金昇玟能打起精神来这件事感到高兴，但他今天难得有些别扭，只冷冷地说好吧，可是我又不想打了，你自己玩去吧！

金昇玟这次没再埋怨他怎么这样，他立刻厚着脸皮问他，那我能不能用你的电脑玩呀。

滚吧，李龙馥大叫，你今天都别想进我的房间了！

金昇玟却满不在乎道，那我无所谓啊，你记得出来吃饭就行。

这句话毫无威慑力，李龙馥的反抗也显得软绵绵的。金昇玟最大的本领就是能在别人嫌他烦的基础上，偏偏把“烦”贯彻到底。李龙馥忍不住说我觉得你这样很恐怖，感觉要是我反锁门死活不出来吃饭，下一秒我就能看到你在窗外倒挂金钟，要我开窗放你进来了。

金昇玟很配合地脑补了下这个画面，觉得他倒挂金钟的样子非常惊悚，于是很慌乱地摇了摇头说我害怕了我们放过彼此吧。

他不甘心，紧接着宣布这次我让你，你小人得志，此为一胜。

李龙馥立刻又反悔了，说算了，游戏打不打打不打打不打打不打。

他一点插嘴的机会都不给金昇玟，一副你今天不给我答应下来咱俩谁也别想放过谁的气势。

金昇玟忍无可忍地拔高声音说你刚刚不是说不打游戏了吗！

他声音一响，李龙馥的重复立刻戛然而止。他先是愣了愣，下一秒却眼皮一垂，语气里添了点无辜：“哎一古，你干嘛对我凶巴巴的呀，我都没说什么。”

金昇玟跳了跳脚，甩了甩手，想发脾气却找不着调，干脆也跟着无厘头起来，说那我不打了，你打我就不打了，你自己找人玩去。

他认真地强调说，你房间不能上锁！上锁我也不会倒挂金钟的！

他俩相视一笑，龙馥忽然拉住他的手问，昇玟会一直陪我闹的吧！

金昇玟说当然了，他心里悄悄补充说，除了我谁还能跟上你啊，但他面上说，你得答应我好好吃饭。

龙馥偏过头，似乎等着他主动。金昇玟主动去抱他过很多次，但是难得有几次会去主动贴上他的脸。但龙馥仿佛早有准备，笃定得像是习惯拿下主导权的人。他又先一步吻住了他，捏住他的脸笑着说我想这么做很久了。他说我上次让你剪刘海是玩笑话，但剪个苹果头吧，答应我，好吗？昇玟，答应我好吗，好想看好想看好想看，你要做听话的いぬ。

他俩就这么又发明出一种新的“学习方法”——把新学的词往生活里胡乱套，算是温故知新。龙馥说我今天学了狗狗这个日语，昇玟说我知道，是いぬ。龙馥笑得直拍手，说你怎么读起来那么像消防车的声音呀。他怪声模仿地重复いぬいぬいぬ。

昇玟却没在意这个，脑子里还在绕着“苹果头”。这是李龙馥这些年来不止一次执念的事情：直播时说过，花絮里对着镜头说过，私下里也提过无数回。

他有些苦恼，第一遍可以说好哦下次试试，第二次说唔记得记得，第三次的时候就会被对方戳着腰窝说在perfunctory(敷衍)，第四回就成了变本加厉地动手动脚，埋怨着骗人。

昇玟问他，为什么那么想让我剪苹果头？

李龙馥顺水推舟，从善如流地说，因为这样的昇玟一定超级可爱。

昇玟受伤地问他，原来在咏卟的眼里，我要靠这种方式才能证明可爱啊。

以牙还牙，举一反三，李龙馥如鲠在喉，被堵得哑口无言，半晌才挤出一句，好吧，金昇玟，你赢了，此为金胜。

金昇玟刻意发出一声“呜嘿嘿”的笑，见李龙馥的视线仍旧落在手机上没搭理他，便又跑到跟前，再“呜嘿嘿嘿”了一遍，这次凑到耳边，还附赠了一个轻轻的“嘿”。李龙馥想要装作没听见都难，索性把手机往床上一丢，猛地扑过去要逮人，却被他一个闪身躲开。

昇玟得意洋洋地弹了他一栗子，等他捂住额头的时候早就跑远了，还隔空冲他做了个鬼脸，转眼一溜烟就撤出房间。

结果出了房门，他又跑了回来，在门口小心翼翼地露出脑袋，刘海遮住了大半张脸，毛茸茸的，嚷嚷着说，咏咏(1)啊，此为第二胜了。

玩谐音玩不过土著，李龙馥大声地喊了回去，你才死定了！

金昇玟听他躲房间里不吭声了，又慢悠悠地踱步到他的房门口，偷偷看里面那人赌气似地盯着电脑屏。李龙馥不大高兴，因为他眉间紧蹙，但又很难看出来他不高兴，因为他虽然撅着嘴，却哼着曲儿，像是因为生气撅得，又像是因为电脑的操作在头疼。

让人摸不着头脑。

李龙馥这人总是会有些格外笨拙的小动作，完全不顾及自身的形象。他有时做着这种小动作时总会有着后知后觉的懊悔，觉得自己不顾形象的样子实在是不忍直视。金昇玟知道他这人谦虚惯了，有时谦虚过了头，害羞没了头，还是露出了些自卑的心思在。他俩都很注意形象，但很少会对着对方的样子评头论足。

在龙馥的口中，昇玟是最好的汪汪。金昇玟问他，好在哪里呀，是脾气好吗？是性格好吗？是你最好的朋友吗？

龙馥一副很纠结的样子，他一本正经地说，因为好这个词可以涵盖好多好多东西，昇玟有太多的好可以夸了，想来想去好像只有这个词最合适了。

但他马上又纠正道，金昇玟脾气不好，喜欢钻空子，喜欢烦人，喜欢捣乱，调皮得要命。

金昇玟不喜欢他后半句话，不满地反驳说，那金昇玟到底哪里好了？

李龙馥很耐心地回答，哪里都好啦，钻空子也不忘让我沾沾光，捣乱还总是让我一眼就能发现，烦人却总会让我心情变好，调皮的时候会却总是那第一个安慰我关注我的人。

金昇玟被他夸得脸红耳热，不满早就被盖过去。他害羞的时候会低头，会脸红，脑袋会忍不住地左右乱晃，会不由自主地到处挠挠。他夸人的时候总会避开视线，硬生生把不好意思藏进别处，会选择不去看夸赞的对象。

所以他俩谁也不知道对方的这个样子。金昇玟很少能捕捉到李龙馥失态的样子，他格外得喜欢偷偷观察，他喜欢李龙馥在那儿说想看他剪苹果头的样子。那是一种带着期许的撒娇，像是春天路边杂草堆里开着的小花，小小一支，却格外得夺目，像他们两只小土狗破茧化蝶振翅的那刻。龙馥的小动作总能够赋予他好多好多遐想，多到他喜欢偷摸着观察，多到大家总是会说呀昇玟怎么又知道龙馥在想什么了呀。

金昇玟在门口迟疑了下，就觉得犹豫是笨蛋的选择。他跑回了李龙馥的房间，靠上他电竞椅的后背，见他的电脑页面不在游戏上，就敲了敲对方头套耳机的顶儿，李龙馥抬头的那一刻，他弯下身，像被夜风轻轻推了一把似的，在他的唇角落下一个飞快的吻。

屏幕的光映在他们脸上，浅浅的，却把那一瞬间的静默点亮了。李龙馥眼里映出的光也跟着微微颤动，像是被这突如其来的靠近搅乱了平静，明亮得几乎要溢出来。那一刻，好像黄昏之后忽然浮现的一颗星，悄无声息，却无法忽视。

(1)听说韩语里好像是个谐音，就是说永远，绝不的意思。
---
