---
title: "倒计时为负的三百六十五个日月"
author: "D"
editor: visual
---
（二）

Best Friend是什么？

金昇玟没想过从李龙馥身上得到这个答案。

他只会说Best friend就是Best Friend啊，然后盯着你傻乐呵。眼睛眯成弯弯的月亮，嘴巴上扬得漏出门牙，什么都说不上来地揉揉你的肩膀，发出莫名其妙的声响。

“嘿呀。”

他说。

金昇玟回答他说：“嘿呀。”

李龙馥用力捏了下他的肩膀，吊儿郎当地又蹦出一句：“啊哒！”

金昇玟学着他，模仿着他的语气，跟着来了一句：“啊哒！”

李龙馥不耐烦了，把他的大名叫了出来：“呀，金昇玟，别给我闹了。”

真是奇怪，好像每次轮到自己，李龙馥这人的耐心就会大打折扣，说话的强调里总是带着不留情面的嗔怒，嗔怒里带着些无奈，像是拿不住下一秒自己会出什么他接不住的招似的。

放屁，明明知道我有多听话，说收就收，金昇玟心想，所以他后退了一步，隔了老远，淡淡地说，我可没闹啊。

偏偏李龙馥不会惯着他，他看着他，脑袋使劲儿地冲他一点，说你过来，金昇玟，金昇玟！

金昇玟走了过去，他龇牙咧嘴，看着他，笑吟吟得。

李龙馥又重复了遍，咬牙切齿地比着夸张的口型说你过来。

金昇玟没有动，他反其道而行之惯了，迎着李龙馥闹没意思，送他一个出其不意的应对方式才是能让面前这个天不怕地不怕，要他在百人舞台面前原地跳旋转芭蕾都能面不改色不觉得害羞的小疯子最佳的攻击方式。

他等到了李龙馥主动地伸出了手去够他，先是攥住他的衣角，把他整个人往自己身边一带，抓住衣摆，再慢慢地爬上了他的后腰。

就是这么一个主动的人，要挟着对方走到自己身边，却死活不肯迈步子，像是从原地打坐的努力中得到了什么值得赌气的快乐似的，整个人的重力快挂到了金昇玟的身上了，那盘坐的两腿依然稳如磐石地呆在沙发上。

如果他站在金昇玟的身后，毋庸置疑，那他绝对会第一时间卸了力，会把脑袋抵在他的肩上，会深深地叹一口气说着好累啊好累啊。这只忘性大的小屁孩会迅速地忘记一切，嘟嘟囔囔地说我好喜欢昇玟的肩膀哦，昇玟真得好男人，后背好稳好扎实。

他的夸奖没心没肺，舒舒服服，相由心生。如果是正对着金昇玟，他也会凑到他的跟前，看着他，盯着他，抿着唇，藏着唇珠，逗弄着他，这会儿反倒是他像只马上要跟着主人出门溜达的小狗，黏着主人，非要从他的身上博得些关注。

但是这太少见啦，金昇玟想，李龙馥似乎总是肆无忌惮地把后背留给自己，把那毫无防备的一面丢给自己。

背后搂住他的成了金昇玟自己，可是他说不出什么李龙馥的后背好宽厚，好舒服，李龙馥好男人这种话。

他努力了半天，最后只成功了一次，摆出了一副无所谓的样子说我爱你Felix。

第一遍的时候他的语调轻浮，只当是玩闹似的调戏，第二遍他看着Felix的眼睛说I love you，却被身后走来的Han打断了。

至少他是这么觉得的。因为他忘了是他紧接着说了句You are my best freind，还是Felix指着他对Han说他是Bad Friend。

答案不重要，这对他们而言都是如此，那是他们成团后的第四年，他们的未来还有很多个四年，有限的四年，但是很多...

多到他想未来他可以找到无数次别的机会说Felix I love you，多到可以拎出自己的队友，说IN最爱Lix，说Hyun-Jin love Felix，反正主语可以是任何人。

为什么呢？金昇玟觉得和成员们相关的问题都不需要答案，就像Lix觉得Best Friend就是Best Friend一样，任何人可以爱Felix，任何人都会爱Felix，但是这个字自己不能和他人共用，Lix爱着很多人，回馈着很多的爱，承受着很多的爱，奉献着很多的爱，但他自私地不需要着那些用来分享的爱。

这是个不需要思考的事，他想，这是个很理所当然的事，就像Felix可以有很多共享房间的临时室友，但是能够把分享生活称为家的只会是他一个；就像Felix会把自己做的甜点分享给身边的每一个人，但是总会第一个过问他的意见。

他说我怕我们昇玟翻脸不认人，所以我要看着你说，我要听着你说你知道了。

李龙馥的活力像是永远都用不完，就像他衣柜里数不尽的老头汗衫。

金昇玟替他从烘干机里垒出一叠白衣时想，真方便，连防串色纸都不需要放了。

一点时尚品味都没有，他一边偷偷保存着对方Ins上发的自拍，一边昧心批评，我肯定能把他拍得更好。

他把李龙馥的衣服叠得整整齐齐，IN说哥在这时候像个老妈子，跟在我们屁股后面收拾东西，金妈妈金妈妈，今天帮我叠衣服，明天帮我盖被子，我们双双把家还。

李龙馥在后头笑得特别大声，他笑得上气不接下气，笑得打了嗝。打得特别汹涌，汹涌到出乎了本人的意料，胸口起伏一次，看向两个弟弟一次。有着摄像头这儿，这打嗝收敛了不少，会懂得收放自如，在脱口而出前戛然而止。

形象保住了，但是嗝停不下来了。

两个弟弟很喜欢这样地看着龙馥，IN一定是喜欢的，金昇玟确认过，我都看不见他的眼睛了。这个视角的龙馥矮上他们一些，总是因此不得不扬起头来回应着他们的关注。金昇玟伸出手，想要去摸他的脸颊，却在快触到的时候又拐着弯似得擦过了他的头发，叹了口气说我给你去那杯水。

李龙馥大概没注意到吧，他侥幸得想着，他的洗发水那么得好闻，香味能够直直地穿透指间，能够打散他十二分的注意力，能够让他们俩镜头前有限的交流中给人乘虚而入的机会。

比如，李旻浩递来的水瓶在他话音落下的那刻已然贴上了李龙馥的右脸，顺带好心地给他捎上了一瓶，冲他扬了扬，笑吟吟地道了声喏。

IN说哥一定没安好心，笑得这么灿烂水里肯定掺了毒，这水我们不能要。

李旻浩二话不说，开了瓶盖就要往IN嘴里灌。

金昇玟心说干得好，不知哪儿窜起的不满被迅速地抚平了。在他打算火上浇油的时候就察觉到自己的衣角被李龙馥悄悄地攥住了。

Felix不是个爱做小动作的人，却在这会儿非要引起他的注意似的，打嗝打得停不下来，一抽一抽，非要等到昇玟的视线回到了自己身上，才凑到他的耳边说：“今晚回去开小灶！”

这有什么好咬耳朵的？金昇玟不解地看向他，却又被李龙馥拽住了袖子，把耳朵凑了过去：“我们俩偷偷的啦偷偷的啦！”

李旻浩白了他俩一样，依旧是温和的调调，问着他们又开始在道什么小秘密。

“Lix呀，笑得跟做贼似的，要做什么坏事了吗？”

他俩对视了下，李龙馥笑得更加灿烂了。

他还在打嗝，昇玟想，这是又瘦了，薄薄的衣物都能勾勒出肋骨，脸上的腮红被嗝一下一下得送上了耳根。

好看是好看的，他移开了目光，李龙馥真是个奇怪的人，他做得每一件事都莫名其妙，但表现得那么理所当然。

他似乎不会去思考事情的前因后果，可他每一次莫名其妙的行动却总能带来深思熟虑的良果。老大以前说Lix就是个没心眼儿的小太阳，昇玟觉得这词形容得并不合适，他明明心眼多得很，八百个心眼子，打破了他过去所认知的教条和规则，却又让人哑口无言得心服口服。

他俩都不想回答老二眯起眼的威胁。金昇玟坏心眼得想，这是我的耀武扬威，我和大家共享的Lix独有的秘密。

他的自信总是在这时候是最膨胀的，他发现龙馥似乎也很喜欢这种同他藏小秘密的感觉。他们会有两人莫名其妙的对话，莫名其妙到两人都未必知道对方在说什么，只是觉得我闹一下你回一下，就是全部的意义。

他们会说悄悄话，全都是毫无意义的悄悄话。Lix会突然跑到他边上，冲着他耳边吹口气说，今天天气好糟糕。又摆出一副我什么都没说的样子，一溜烟儿地跑去了其他人那儿，独留他在原地发愣。

天气糟糕吗？金昇玟很少会注意到天气的变化，但他承认，这是个很影响自己灵感和情绪的充分非必要条件，他跟在李龙馥的身后，说是啊，好糟糕。

龙馥转身，也不知道是听没听到，视线掠过了他，定在了他的身后，在同他对上的前一秒快速地收了回来，又一蹦一跳地跑去找其他队友了。

队友常说Seungmin是个很闹腾的人，说他这人非常尽职尽责，由外向内地将狗塑履行到底。私下里李龙馥喜欢冒出一句，还好吧，我觉得。要是有个镜头在，那镜头就会在这时候就成了他眼里的香饽饽，身后的纷纷扰扰与他便无半点关系了。

李龙馥的确能这么说，金昇玟想，这是我对他的纵容。我怎么闹得动他？不招惹的时候他偏偏喜欢在我面前晃上一下，跑去闹他的时候他又能尽数接收，闹大了...

金昇玟从来不敢在李龙馥面前闹得太大，他对他总是小心翼翼的点到为止。

他俩就是这样得默契，一对视就知道彼此都是故意的，这临门一脚就等着彼此踹着呢，等着开大了的玩笑往着对方身上甩锅。

烦死了，金昇玟每次一想到这个就有些烦躁，李龙馥真是个奇怪的人，他又在想，八百个心眼子，绝对有八百个心眼子！

这八百个心眼子的人仗着比我大的那几天，使劲儿得闹我，搞得我像个小孩子似得。可偏偏这时候这家伙就会吝啬地丢下一个心眼子，非要跑到我的跟前，Seungmin来Seungmin去得说我是个成熟的男人。

忙是挺忙的，网络上的梗也是不忘落下的。

说着说着还非要勾肩搭背上，小小的身子大大的力量，赖在自己身上，抠都抠不下来。

不好好吃饭的人，都不知道哪儿来的力气。

下次吃饭的时候还得是他盯着。Lix说我们Seungmin西把它当作了义务，这是他什么时候说的？似乎是很早，早到了他都不记得这句话是始于玩笑还是感激。

他和龙馥说，好的，那麻烦你配合我的工作哦。

龙馥看着他，突然神情很严肃地说，昇玟呐，有时我真搞不懂你。

于是他们决定在晚上的开小灶环节里加上促膝长谈。

金昇玟在那一晚明白了，原来李龙馥的确有八百个心眼子，这八百个心眼子全用来理解他这个室友的喜怒哀乐了。

挺好的，他想，这也是我们有默契的地方，他绝对想不到，目前他室友的喜怒哀乐全跟着他的八百个心眼子跑，前阵子的懊恼也是因为跟不上这八百个心眼子而给气得。

哪想越是跟不上，这心眼子掉得就是越多，形成了个永不交叉的平行线。

李龙馥是个自我消化能力很强的人。金昇玟想，我是不理解他，他又何尝不是如此。但此人就人际交往方面的归纳能力相当得精炼，把这世间的十斤八两统共就相处的舒适程度划分为两类，好人和坏人。	

金昇玟常常觉得自己被夹在了两者之间--因为龙馥会说，呀昇玟，又要干坏事了！你这个坏人；可他又会在哭哭啼啼的呜咽声中说昇玟你是个好好的人哦，怎么会有你这么好的人。

一把鼻涕一把泪，手里的纸巾一张接着一张，昇玟习以为常地让他靠着自己的肩膀，等着半边的肩膀湿出了触感，才如临大敌地想起来今天穿的是一件白色的卫衣，而龙馥的妆只卸了一半。

他艰难地握住对方搂住自己的胳膊，向他确认是不是没卸完妆。

龙馥哭得伤心，听了这话跟开了大闸，顷刻间嚎啕大哭了起来：“没有哇，我，我现在肯定特别丑。”

李龙馥不爱哭，因为他的眼泪几乎不为自己流。他会因为粉丝感动，会因为电影的细枝末节生情，却总是对自己忍痛的能力嗤之以鼻。

所以那次是因为什么事情而流泪？金昇玟不记得了，他很少会记得龙馥为其他人哭的原因—除了为粉丝，不然，他想，龙馥在他的心里也会成为一个爱哭的小孩。

他替李龙馥记着，记得他从医院回来时走起路来会摇摇晃晃，记得雀斑上沾着泪珠，脸蛋上挂着泪痕，声音是在颤抖得，牙关咬得紧紧，但是不忘记主动地和经纪人说哥谢谢你，明天见哦，非要哥在他面前发誓今天一定要把他坚强男子汉样子和妈妈妹妹好好一番强调。

哥关上门的咔嗒声一击重锤地打得龙馥膝盖一弯，一个踉跄就被金昇玟揽住了。

“回头一定要和哥说，让他关门的力气小点，”Felix埋在他的怀里，闷闷地说，“吓到我了都。”

金昇玟拍了拍他的背，说今天去医院去了好久啊。

龙馥贴着他的衣物，呜呜得深吸了一口，说那是，我可厉害了，医生说明天的舞台绝对没问题。

是吗？金昇玟很少会拆穿他，他看着龙馥对着他的发旋，这是对方看不见他时总是会暴露给自己的软肋，金昇玟迷迷糊糊地想，李龙馥是个脆弱的人吗？

李龙馥不是的，所以金昇玟点点头，两手就着两边埋进他的头发，一通乱抓，说，好，厉害的咏咏，来吧，我们厉害了这么久，也应该休息休息了！

龙馥微微扬起头，抬眸端详起了他。

金昇玟别开目光，收回手就要松开他，就感觉这牛皮膏药又贴了上来。

Felix认真地说，今天带我打游戏上分！

这要求提了跟没提似得，金昇玟拒绝了，他说不行，你今天得休息。

Felix的无理取闹果然虽迟但到，他开始耍赖似得越抱越紧，说昇玟啊昇玟啊我想玩，好想玩！

他开始学着金昇玟给他编昵称的样子，叫起了SeungSeung，又试着改成了MinMin，结果先一步给肉麻到了，呕了呕说Seung啊！陪我玩呗。

金昇玟拿他这样没有办法，是该发火说你不该这样？还是说你怎么这么软骨头！他又懊恼了起来，李龙馥这人，蹬鼻子上脸的事儿真是手到擒来，明明是他先招惹的，结果偏偏先后悔上的总是他自己。

他不比其他几个哥哥，龙馥这小身子板他也得两手支着力，他憋了半天，说你先站起来。

李龙馥说我不，但是身子往上扭了扭。

可惜他忘了眼前这人不比他那些能让他当杆儿乱爬的哥哥们，想着给室友减点负担不成，反而把他连带着一同拉了下来。

金昇玟话还没说，李龙馥就像是预判了他的反应似得，替他嗷嗷得叫了起来，身子压过来时不忘送出手背来替他垫腰。

前者这会儿倒是突然力大如牛了起来，身子稍稍蜷了蜷，把龙馥往自己怀里一带，啊呀地叫了一声应着倒了地。

他左手扣住龙馥伸向他后腰准备牺牲的手，两人叠叠乐似得压在了客厅的地毯上。

这地毯柔若云絮，素朴淡雅，明媚的乳白色铺散着，一脚踩上去像是拂过一片草甸；这才买回来没多久，跟着薰衣草香的洗衣凝珠在滚筒里滚了两圈，拿出来刚用上，沁人心脾的香气跟着两人身上的热气一簇一簇得往外窜。

娘不拉几的地毯，当初彰彬一次来送东西时只第一眼便脱口而出，后又不忘问着房门里出来的龙馥说呀Yongbok啊，怎么挑了个这样的地毯。

龙馥揉着眼睛打着哈欠摇头晃脑地走出来，瞥了眼冷笑了声，道哥你别问我，去问Seungmin，他选的。

娘不拉几是什么意思？他不懂这个词。

说咱们不够Namja，金昇玟抱臂站在自己的房间门口，冲着徐彰彬吊儿郎当，挑着眉挑衅道：“哥经验丰富啊，这么敏感。”

彰彬作势要打他，金昇玟一蹦三尺远，逃归逃，不忘提醒他哥脱了鞋再进屋，顺带还给龙馥捎上了一句，说厨房锅里给他煎了鸡蛋，得趁热吃了。

金昇玟没事就喜欢撩拨他的哥哥们，从来没打赢过，但练就了一身无人能够超越的逃跑技术，力求最小空间最大化利用，把狭隘地方的逃跑线路发挥到了极致。

他蹦到厅里的沙发上，直接一跨两级，上了靠垫，未雨绸缪地计划着如何能够跃过来拦路的彰彬，冲去厨房，从龙馥的虎口里抢救出剩下的一片或两片煎蛋。

结果没想彰彬的戏剧细胞格外得给力，鞋子甩出去的后一秒，一个四脚朝天的狼狈就被这地毯绊出来了。

那头端着煎蛋的李龙馥出了厨房就看到沙发上金昇玟倏得亮起的眸子，炯炯有神地看着那张因为不够namja被认为削弱了影响到本人气场的毯子，他就知道，他们宿舍下一个月洗衣机的新宠是有了，不够男人的地毯竟然随随便便地打倒了一个公认的强壮男人！

龙馥不需要他虎口抢蛋，他会帮他把蛋分好，会替他摆好餐具，顺道再夸上一句我们昇玟太男人了，蛋越煎越好了。

彰彬赖在地上骂骂咧咧，说煎个蛋都能很男人，我吃个蛋我岂不是男人中的战斗机了。

李龙馥这回的不懂多半是装的，他问他哥，什么？

他装不懂的时候抛出的问题总是跟着他的脑袋一样，听着像是转了好几个弯，最后飘飘然地落到了你的耳畔，脑袋也适时地歪到一边，有时为了更夸张的效果，会再多余出些位置给眼白，把眼皮子撑得极开。

这是很夸张的说法，龙馥说昇玟是在借机骂他。

金昇玟很聪明，描述必然是有目的性，他顶着腮威胁说，昇玟我还不了解你吗？

金昇玟被他气笑了，说你能不能先从我身上下去，又不是要亲我，还赖在我身上趴那么久。

他这话就像赌气，像是闹定了龙馥不会亲他。因为龙馥的确好像不会这么做，他亲过很多人，Han，老大，老三，还有忙内，来者不拒，却之不恭，这群人里就是没他一席，镜头里外，人前人后，哪怕是独处。

李龙馥又不吱声了，他每次都是这么游刃有余，不说话地抬头，不吭声地看着他，把话语权丢到了对方的手里。

实则的掌权者明明还是他。

可这次金昇玟接不住了，他尝试躲过龙馥的视线捂住自己的脸。

“逃什么逃啊！明明是你自己说。”龙馥紧紧地抓住他的腕部，跨坐在他的身上，十二分的力气全压在和他的较劲上了。

“你有没有病人的自觉了啊，”金昇玟脑袋转向另一边，语气急了起来，他的声音要高上许多，这会儿听着有些急促，尖锐凶狠了些，“不要碰我，快下来。”

他先是用韩语，后来换成了英语，说Please don't touch me， 手上受的力却不见得收敛，又拔高了音调说stop doing that, getting off me!

他想得好好的，事不过三，他要再用英语说一遍，让龙馥乖乖地从自己身上下去，等第三遍他还是不听话的话，他就要发力反制住对方，腾出一只手，能够揽一下他刚疗养好的腰，在伤害最低的情况下把他撕下来。

可龙馥从来不是把机会拱手让出来的人，他在金昇玟叫着Felix的全称时就哑了火，在他说第一声getting off me时低了头。

金昇玟正要用力时，忽然觉得左颊被什么烫了一下，一滴温热的液珠滑落下来。他猛然回头，唇角擦过一丝咸意。抬眼，源头已在眼前：那双瞳孔正在缓慢散开，空空地望着他，像是不辨是酸涩还是别的缘由，眼底水光氤氲，终于从眼角漏出一点。

他今天没有戴美瞳。金昇玟在那片刻的失神中选择了退让。几乎要忘了，那双瞳色与他浅棕的原生发丝一样独特，有别于大多数亚洲人的深色。也正因如此，他才能在并不昏暗的灯光里，清晰看见那一圈逐渐扩散的黑色。

该说句话，金昇玟意识到，他们不适合长时间的沉默。

他心里知道，沉默拖得太久，反而更显尴尬。也许此刻该说一句“对不起”。但对于成年人，这两个字实在艰难。他张口，又闭上，再张开，终于像是要下定决心。

却在那一瞬，被龙馥一把捂住。

他弯下身子，姿势生硬得近乎小心，隔着手掌，贴上了他的唇。
---
