---
title: "倒计时为负的三百六十五个日月"
author: "D"
editor: visual
---

（六）

队友们常说咏卟噶是个思维跳脱的人，总能冒出些奇妙的点子。大家会夸他有主意，想象力丰富，创造力十足。金昇玟就偏要插嘴说他是海绵宝宝，不着边际，边说边学着海绵宝宝的发音，“咏卟噶来咏卟噶去”。李龙馥当着大家的面不好发火，只能顶腮、投眼神警告。金昇玟偶尔会装作不知，一脸“成熟男人”的大度回应，大部分时候则干脆眼盲耳聋，视线一转，耳朵一进一出。

龙馥的神色越是直率坦诚，他就越难以承受那样的对视。金昇玟说龙馥的眼睛漂亮。他不太会夸人，朋友们笑他懵懵，呆滞的时候藏不住事儿，明明一动不动，实际上脑子里的想法一个接一个往外蹦。当初刚认识这个来自澳洲的小子的时候，比起其他人对大金表的惊叹，他注意到的只是那双漂亮的眼睛，藏在雀斑之间。那时候的眼睛还没有如今这样明亮，带着离家雏鸟的慌乱。金昇玟用韩语开玩笑地说了句你的眼睛好看，结果李龙馥根本听不懂，就盯着他，好像个呆瓜。

就是个呆瓜！金昇玟后来这么跟他描述，无辜地看着我，特别得委屈，像是我下一秒就要开始打你，吓我一跳哦！

李龙馥说好吧，那你还是觉得我呆瓜吧，我只是没有听懂你在说什么。

金昇玟很惊讶地问说你难道还记得那件事吗？

应该？李龙馥想了想，我不记得细节了，但和昇玟的初见一定很愉快吧，因为我第一眼看到你就很喜欢你。

他又反击说这不公平，昇玟其实也是呆瓜——一直都是。他学金昇玟做鬼脸，学得不太像，总是会先把眼睛睁得老大，企图通过吐舌来表现出狰狞的神情。

金昇玟不理他，李龙馥就又自顾自地夸起了昇玟的好。他细细点来，说昇玟是第一个告诉他不要用吃柠檬这种荒唐的方法去掉雀斑的人...

结果这句话还没说完，金昇玟就把他打断了，他说咏卟噶，不要再重复啦！

李龙馥批评他说，不行，我就是要重复，以后金昇玟对我做的好的事越来越多，那我就重复得越来越多，你不是说我是海绵宝宝吗？海绵宝宝最能装了。

金昇玟想说我其实从来没觉得你像海绵宝宝，就是觉得你们大概能搭边的只有宝宝和想象力。但是龙馥在昇玟的眼里五颜六色，他才是那个百变的，可他也不是孙悟空七七四十九变。他只是单纯觉得李龙馥的色彩太鲜艳了，太明丽了，好像能成为任何想象出来的主角。但他又是李龙馥，这样的李龙馥，有时像是一个凭空创造出来的幻象，而在那一瞬间，却又远得让人触碰不到。

他说Stop！我们不谈过去，我不要听你说话了。

这次李龙馥没有帮他给他机会打岔了，他很明确地问昇玟你到底在怕什么？

金昇玟说我怕？怕什么？有什么怕的？我可没有在闯鬼屋的时候直接给人跪下。

李龙馥哈了声，冷笑说你再给我提这茬，我手动让你跪下。

可惜他只有嘴上说说的功夫，到底还是没有落实行为的能力，就又被金昇玟自说自话地关进了房门。

李龙馥自觉地跑过去开了门，果然见昇玟还站在门口，手缩进宽大的卫衣袖子里，像个毛绒绒的团子。
其实他在家里很喜欢穿短袖，不过这会儿套了件卫衣，手又不由自主地藏了进去，他问Lix会不会有的时候不懂我在想什么？

龙馥本想跑过来报复，被这问题打了个猝不及防。藏在衣袖里的昇玟的手在灯光下呈现出了一种迷蒙的土黄色，有些好笑。他伸手去捣乱，把昇玟的袖子往上卷又放下来，借机找点存在感

金昇玟手握着拳，死攥着衣袖，一点可乘之机都不给。他逃避问题的方式就是做一个无声的哑巴，所以他开始自顾自地和龙馥的手较起了劲儿。

李龙馥玩不过他，只好悻悻地收回了手，说这个答案对我来说不重要啦。反正我听不懂的时候你也能看出来，觉得重要的话都会直接和我说。

金昇玟踯躅地想，如果我这会儿追问一句，那我不解释你是就直接想翻篇算过去了？我的想法在你看来到底重不重要？

他俩的默契总是在这时候起到了作用，龙馥说金昇玟不解释的话，要么就是没必要，要么就是不想让我知道。昇玟不想让我知道的事一定有他自己的理由，所以我不听也无所谓。

看吧，李龙馥就是这样的一个人，他的无私是一种本能，因为他思考问题的出发点从来都不是自己。

所以如果金昇玟说重要，那他一定会说好嘛，那我下次一定多问问，如果金昇玟说只是好奇啦，他也就会说一句，现在知道了吧。

金昇玟怎么回答？

他心虚但是佯装胸有成竹的样子说那太好了，以后可以瞎诓你了。

这是在宣告矫情的戏码点到为止，李龙馥直接伸手去掐他说你给我把昨天喝的椰汁吐出来。

力道却轻得像在逗弄。他捏着他的脸，把他逼得抬起眼来。昇玟正要开口，眼神在灯光里撞上了李龙馥的，怔了片刻，嘴角动了动，笑意却没能真正浮出来。空气里赌气的火星忽然变了味，暧昧得让人呼吸都乱了一瞬


昇玟闷声说：“好啦，我怕你了。”

李龙馥要拍拍他的脸，开玩笑说不怕，结果他偏没捉住这个机会。金昇玟用小拇指在他掌心挠了下，顺势握住了他的手，又在他掌背上落了一个吻。

他没问过李龙馥，两人贴在一起的时候就像两只小动物在面对大雨磅礴的浇灌后有一种劫后余生，相互依偎的彷徨。动作总比思绪先一步，但这并非一时冲动，相由心生或许是个更合适解释的词。

在他轻咬的间隙，李龙馥又复盘似地问了一句，你为什么不回答我呢？

回答你我在怕什么？金昇玟替他在心里把这句话补上了，他想我的确没在害怕，和你聊聊过去挺好的，探讨当下也很不错，你还很喜欢和我说未来我们要怎么样。我觉得很好，都很好，只要是和你聊，没什么是不好的。

于是这次邀请的人成了他，他说龙馥啊我们做爱吧，做爱的话一定就能知道答案了吧。李龙馥很少有被他的直言不讳吓到，他端详着他，看着他像是在看一个陌生人，叹了口气说金昇玟不要这样。

不要这样是哪样？金昇玟觉得自己被拒绝得很狼狈，他说你不是一直很想做吗，我也很想做啊，我们为什么不做呢？

龙馥把头靠在他的肩上，脸蛋儿贴着他的肩膀，发丝挠着他的下颌。可过了一会儿他觉得不大舒服了，就把头埋向了他的胸口，他有点闷闷不乐了，说昇玟我觉得不对。

金昇玟突然觉得有点好笑，毕竟这场没头没脑的邀约，从一开始就带了点怜悯与笨拙的求生意味，好像在荒原上瑟缩的小动物，裹紧了身上的毛，只想靠近彼此的体温，所以他说，那龙馥啊，喜欢我一下吧，做爱的时候喜欢我一下吧，我也喜欢你一下，可以假装是爱人的喜欢，也可以远超于爱人的喜欢。

李龙馥低低笑了一声，却带着自怜的悲伤，他说你不要自言自语，你讨厌死了。

他的目光依旧很清透，只是看着金昇玟的目光里多了点脆弱。他说金昇玟我想和你好好谈谈的，可是你不想听我说，这就是你很讨人厌的点，我不会生你的气，我怎么生得动你的气啊懵懵。

他很少这样叫他，他说这个称呼很可爱，但不特别，因为懵懵是大家的懵懵，大家都这么叫，所以他叫就不特别了。可那一刻，他还是喊了出来，声音轻轻的，不急不缓，像是顺口，却又在空气里留下了一种说不清的亲昵。明明只是和别人一样的称呼，却因从他口中落下，仿佛多了一层只属于他们之间的意味。

金昇玟的脸色很不好看，这一刻的龙馥好像又离他远去了，是龙馥主动离开的。他急切地握住龙馥的手，说我哪里有不好好听你说！

他的声音比平时高了半度，像是被逼急了的小兽。李龙馥怔了一瞬，想要回话，却被昇玟眼里那种濒临失控的神色堵住了。那眼神里有怒，有委屈，还有某种说不出口的渴望。

金昇玟的声音里带了哭腔，他在发抖，可是他没有眼泪，他说龙馥今天真得好冷啊，真得太冷了。

他说得有点语无伦次，先说“你一定不要和别人讲”，又说“我对自己很不满意”，提到梦里的童年，话题一转，又成了“觉得唱歌有瓶颈”。像是所有藏得很深的念头，一口气全被逼出来。

李龙馥托着腮听着，没打断他，只是缓缓地应声说我知道，昇玟上次半夜从练习室回来的时候还跟我说那天的星星很漂亮。

他的语调平静而笃定，像在替他收拾那些碎片似的，说我记得特别清楚，因为那天我心情也不好，然后昇玟给我带了热乎乎的炸鸡，说因为看到我在泡泡里说很想吃，他自己也很想吃，所以就顺带看过来了。

他一件件说下去，把那些昇玟零散、飘忽的情绪拢在怀里，说昇玟还提到那天在炸鸡店碰到了STAY，说自己唱了之前STAY们推荐的歌，难度高但是唱上去了，还把自己的录音音频分享给了我。那时候可得意了，还让我在你发音的时候摸着你的肚子，告诉我气沉丹田时这种硬邦邦的感觉。

李龙馥笑了一下，眼神却很认真，他说你看是不是，我都记得呢。

昇玟，瓶颈不是停下，也不是倒退。进步从来不是一蹴而就的事，每一步都算数。走得快不是问题，忘了自己怎么走过来的才是。你没忘，我也没忘。

金昇玟怔了怔，唇瓣颤了一下。他想说谢谢，又觉得这两个字太浅。他心口涌出的热气像突然被点燃，忍不住去靠近，把额头抵在龙馥的肩上。言语失去重量的时候，他说龙馥，不要推开我好不好？他说我该拿你怎么办？他又说，我该拿自己怎么办？我觉得我有时候真得像个烦人的大叔，畏畏缩缩的。

李龙馥一时间没说话。他原本放在膝盖上的手僵硬着，像是在犹豫。昇玟颤抖的声音一次次撞进耳膜，那句“烦人的大叔”更让他皱起了眉。像是谁胡乱给的评价，被他拿来贴在自己身上。他忍不住低声埋怨说，什么烦人的大叔啊，那我还比你大七天呢，我是不是可以升级老头了？

他想替金昇玟理理遮住脸的刘海，想让这人的哽咽不要尽数咽进自己的怀里。可动作还没落下，就先被人扣住了胳膊。昇玟在抽泣，偏偏还俯身对着他颈侧轻轻吹了两口气。湿漉漉的睫毛扫过皮肤，不长也不浓，却挠得他浑身发痒。

每个人都说Lix是超棒的人，金昇玟闷声说，可是没有人知道你到底有多棒。

龙馥被他锁在怀里，嗓音却轻快了些，那也没错，大家都说昇玟是个皮狗狗，可是没有人知道你到底有多可靠。

他很喜欢金昇玟的比喻，昇玟总能捕捉到别人忽略的细节，龙馥眼里的金昇玟脑子里也装着一个奇妙的世界，会把身边重要的人想象成礼物般滚进生命里的石子，会把龙馥幻化成各种古怪又鲜活的虚拟角色。他看世界的方式那么细致，那么温柔，好像在日常的褶皱里也能找到光。

这样的昇玟太特别了，特别到让人想要紧紧拥抱，龙馥无数次想告诉他，你其实就像Youtiful歌里说的那样，much more amazing than you realize。他下意识地靠近，先是停在半寸的距离，呼吸在空气里纠缠不清。昇玟没再说话，眼神却像是脆弱又倔强地推开，又像是小心翼翼地邀请。龙馥直直地望着他，没有推开。

那一瞬间，空气似乎骤然安静下来，昇玟胸口的颤动和龙馥的呼吸撞在一起，像是无声的回答。距离被夜色稀释，半寸的空隙在呼吸间融化，像风落进海面，自然而然地合为一体。

---
