---
title: "倒计时为负的三百六十五个日月"
author: "D"
editor: visual
---
（一）

天蒙蒙亮的时候，他们下班了。

金昇玟眯着眼时，被自个儿这突如其来的遣词造句给逗乐了，觉得这话前后的矛盾程度不亚于身后那人精神百倍地哆嗦着说他好困好困的埋怨。

他转过头，发现当事人的不以为然，甚至还留有了几分的兴致地腾出一只手，搭在了他的室友肩上，我们龙馥儿啊我们龙馥儿啊得唤着。

是不是困了？他听到对方问。

他的室友怎么回答得？

明明困得大眼眸子成了缝，脑瓜子左右晃悠着，一头卷毛横七竖八，向着四面八方，听到了队友的问话却像是一个激灵，特别自豪地蹦出一句，我这两天就睡了2小时！

话罢摇摇晃晃地就近找了个椅子就是一躺，眼睛一闭，睡着是不会睡着的，因为那唇角翘得老高了，得意得很，也不晓得是不是忘了还没有回答问题，嘴里只顾着嘟囔着，我要睡一会儿啦睡一会儿啦，就一会儿哦一会儿。

路过的彰彬立马脱口而出：“好！我们的IN，就眯一会儿！”

他看来真得累坏了，金昇玟想，李龙馥选择把身上的毯子盖过了脑袋，蜷成团的身子吝啬地背过了他们。

甚至都愿意勉强接下忙内的身份了。

李龙馥就是这样一个人，他有精力有力气的时候，就会陪着你闹，不想浪费时间或者没有精力浪费时，他总会出现一些很奇特的少爷性子。

不闹脾气，不发火，就是不吭声，不挣扎，平等地对面前的一切视而不见。

大伙儿认识了个把年了，都说李龙馥的性格是最好摸透的，摸不透也不要紧，因为他是一个真挚的天使，真挚到喜怒哀乐会溢于言表，会形于言色。

开心是最好不过的了，李龙馥的笑有一种魔力，能吹散乌云，罅隙漏光，雨天转晴，这些来自身边人竞技似的攀比夸奖把他的笑层层叠叠似得越垒越高，而队友们似乎觉得这种在媒体面前的争先恐后是一场群雄逐鹿，却全然不顾这头鹿是否早已被举到了众星捧月的高度。

我不一样，金昇玟想，旁人眼中举头白玉盘中一颗珠，欲摘不得攀，却是我轻轻举手摘取来。

不开心也不打紧，李龙馥的负面情绪就像他翻身起床的本领一样，后者一秒即动，前者转瞬即逝。他会生气，会不满，会不屑，但是他会一个白眼翻过去，唇角向下眉一紧，眸深一转撇下嘴，事情就跟着翻了篇。

记仇吗？记住个九就不错了。

金昇玟嘿嘿得自顾自笑了起来。他总是这样，其他人提防着他的猝不及防，说他每次露出这种表情时一定是有什么坏心思上了头。

李龙馥却在这时候露出了他那双独有的漂亮眸子，说昇玟啊！呀！金昇玟！

每次叫大名的时候非得要呀上一声，说得好像有多少威慑力似得，金昇玟磨了磨牙，盯着他，还在笑，却不理他。

李龙馥又埋怨起了彰彬，他说都是哥的错，都是哥，刚刚又把我叫成IN了。

金昇玟这回跟上了，他模仿着徐彰彬的语气重复了遍道：“好！我们的IN！就眯一会儿！”

门外传来了正主大声的回应，嚷嚷着问怎么了怎么了。

金昇玟心下一惊，道完了，这回要真生气了。

好奇怪，默契总是在这时候息息相通，他看向了沙发，确定了对上他的视线，李龙馥重新缩回了被子里，没有背过身子，但是拒绝和他视线再接触。

真得很奇怪，金昇玟抱怨，这份抱怨就像是被偷喝的龙馥加了糖的冰美式，到底是谁说这家伙是天使的？和自己发起脾气来总是让人摸不着头脑，好像偏偏是脾气找上了门，逮着个机会就要冲自己耍耍性子，也只有对他是这样，像是不知道自己的语气变了调，像是不知道天使的光环碎成了恶魔的小角。

奇怪的事太多了，他们这俩几乎截然相反的性格，在对视的沉默中却能达到心照不宣的理解和共识。队长总说Lix呀你和Seungmin是不是有秘密了，你们哦，偷偷摸摸在说些什么？

他说这话时两人隔着条过道，带着口罩扣着帽子，不过是隔空冲着对方左右摇了摇脑袋。

有秘密吗？金昇玟想，那就有吧，就是没有也得有。

嘿嘿，秘密。

他想，听到这话时胸膛承载的心脏有力的跳动告诉他，就是这个秘密。

过去有个说法，说人在年轻时总是充满激情和想象力，容易自以为是地把对情感关系的沉浸等同于了解一切，完全看不到其中的盲目性。

金昇玟小大人似得觉得，我不是这样的人，我可拎得清了，拎不清的是我那个室友。

那个不知道大家在笑什么就会跟着一起傻笑的笨蛋。

他问龙馥说Lix啊，你懂哥哥们在逗你什么吗，你就跟着笑。

问这问题时龙馥还在休息室吃饭，嘴里的东西来不及咽下。

他就是这样的一个有礼貌的傻子，金昇玟想，无论做什么事，但凡要倾听时，都必须注视对方的眼睛，回话时也总是努力地尽可能地咽下嘴里的食物，认认真真地作答。

傻子说我不知道呀。

明明是个沉沉的低音，说起话来确实很软软糯糯，非要带了点上扬的尾音，黏黏糊糊带了钩似得。

不知道你还跟着笑，就你好欺负，金昇玟不自觉地跟着放平了些调调。

应该，真得很好笑吧，李龙馥想了想，又补充说，大家都在笑哦。

金昇玟差点脱口而出，怎么，大家都在笑你就要跟着笑吗？怎么假笑都跟真笑似的。

但他说不出口，他自知这是反话，那怎么会是假笑？Lix的假笑是会抿着嘴，藏起翘起的唇珠，唇角只留些许的弧度，瞪圆了眼眸子，留有的眼白，抬起的凌眉，整张脸总是一副誓要把“我在假笑”的宣言扬名天下的架势。

于是他改口了，改得生硬又逞强：“那也不见得你每次都跟着大家一道笑哦。”

他想说上次，上次什么时候？他非得要说出一次，说出一次他露出恶魔尖角的样子，说出这个天使露出的恶魔尾巴。

“啊。”李龙馥愣愣地看着他。

他都不在回忆，金昇玟想，那双漂亮的眼眸子既没有左飘，想着找一个合适的借口，又没有右移，跟着他的‘上一次’一起回忆，好像只是一种自然而然的习惯。

“那可能是因为昇玟你没笑吧，”他的筷子抵着下唇，像是在嗔怪，于是，两颊又鼓了起来，“如果你不跟着大家一起闹的话，我就知道，那肯定不是什么真得很好玩的事了。”

妈的，是不是恶魔不知道，但是自己一定是最先被净化的那个。

他没有回答，这是他没有答案时一贯的逃避方式，李龙馥冷不丁地冒出了一句：“昇玟啊，这个牛排没你煎得好吃哎。”

他很认真地打量着牛排，翻了个面，又翻了回来，含含糊糊地说昇玟做牛排果然厉害啊。

得了吧，金昇玟心说，比不过你这个澳大利亚来的孩子好吧，谁不知道你在哄我啊，我需要你哄吗？

需要啊。

于是他跟着黏黏糊糊地说，啊那，那我回去给你做。

李龙馥怎么回复得？

他大叫：“啊啊啊啊啊啊！”

金昇玟学着他，也跟着：“啊啊啊啊！”

李龙馥不甘示弱地往上又拔高一个八度：“啊啊啊啊啊！”

这次金昇玟没来得及跟上，因为半路从椅子后杀出来了韩知城，一声惊天动地带着弯似得“啊啊啊啊”不光成功截胡，也顺利地引来了请他们稍作安静的Staff。

李龙馥收好餐具，窜到他跟前，非要和他好好对视，再三确认地说，我们说好了哦。

嗯，他回道，好烦啊这个人，每次和他一对视，就会忍不住跟着笑。
---
